# Change these first
owner: Infobourg # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Events
    url: https://events.infobourg.org
  - name: Minecraft
  - name: Map Minecraft
    url: https://minecraft.infobourg.dev
  - name: Portainer
    url: https://portainer.infobourg.dev
  - name: Nginx
    url: https://nginx.infobourg.dev

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.infobourg.dev
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.png
  name: Infobourg
  introTitle: "Infobourg Status"
  introMessage: This page shows **real-time** status of the Infobourg websites and services.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
