owner: Infobourg
repo: status

sites:
  - name: Events
    url: https://events.infobourg.org
    expectedStatusCodes:
      - 200
      - 201
      - 404
    icon: https://events.infobourg.org/assets/favicons/android-icon-192x192.png
  - name: Minecraft
    check: "tcp-ping"
    url: $SECRET_MINECRAFT_SERVER
    port: 25565
    icon: https://www.minecraft.net/etc.clientlibs/minecraft/clientlibs/main/resources/favicon.ico
  - name: Map Minecraft
    url: https://minecraft.infobourg.dev
    icon: https://www.minecraft.net/etc.clientlibs/minecraft/clientlibs/main/resources/favicon.ico
  - name: Wiki
    url: https://wiki.infobourg.org
    icon: https://static.requarks.io/logo/wikijs-butterfly.svg
  - name: Portainer
    url: https://portainer.infobourg.dev
    icon: https://www.portainer.io/hubfs/Brand%20Assets/Favicon/Portainer%20BE%20Favicon%20icon.svg
  - name: Nginx
    url: https://nginx.infobourg.dev
    icon: https://www.nginx.com/wp-content/uploads/2019/10/favicon-64x46.ico

status-website:
  theme: night
  cname: status.infobourg.dev
  logoUrl: https://raw.githubusercontent.com/Infobourg/status/master/assets/icon.png
  favicon: https://raw.githubusercontent.com/Infobourg/status/master/assets/favicon.png
  name: Infobourg
  introTitle: "Infobourg Status"
  introMessage: This page shows **real-time** status of the Infobourg websites and services.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

assignees:
  - IliasRedissi
